import React from "react";
import {
  Card,
  Form,
  Select,
  DatePicker,
  Button,
  Table,
} from "antd";
import {
  SearchOutlined,
} from "@ant-design/icons";
import HeaderTittlePrintFrom from "../../SharedAllListFrom/HeaderTitle/HeaderTittlePrintFrom";

const { Option } = Select;

const CnfVolumeStatementImpSeaPage = () => {
  const columns = [
    { title: "SL", dataIndex: "sl", key: "sl", width: 60 },
    { title: "Job No.", dataIndex: "jobNo", key: "jobNo" },
    { title: "Ref. No.", dataIndex: "refNo", key: "refNo" },
    { title: "LC No.", dataIndex: "lcNo", key: "lcNo" },
    { title: "Consignee", dataIndex: "consignee", key: "consignee" },
    { title: "Shipper", dataIndex: "shipper", key: "shipper" },
    { title: "HBL", dataIndex: "hbl", key: "hbl" },
    { title: "MBL", dataIndex: "mbl", key: "mbl" },
    { title: "Carrier", dataIndex: "carrier", key: "carrier" },
    { title: "Commodity", dataIndex: "commodity", key: "commodity" },
    { title: "Model No.", dataIndex: "modelNo", key: "modelNo" },
    { title: "PCS", dataIndex: "pcs", key: "pcs" },
    { title: "Origin Agent", dataIndex: "originAgent", key: "originAgent" },
    { title: "Destination Agent", dataIndex: "destinationAgent", key: "destinationAgent" },
    { title: "ETD Date", dataIndex: "etdDate", key: "etdDate" },
    { title: "ETA Date", dataIndex: "etaDate", key: "etaDate" },
    { title: "POL", dataIndex: "pol", key: "pol" },
    { title: "POD", dataIndex: "pod", key: "pod" },
    { title: "QTY of Container", dataIndex: "qtyContainer", key: "qtyContainer" },
    { title: "VOL", dataIndex: "vol", key: "vol" },
    { title: "QTY", dataIndex: "qty", key: "qty" },
    { title: "GWT", dataIndex: "gwt", key: "gwt" },
    { title: "TUES", dataIndex: "tues", key: "tues" },
    { title: "TOS", dataIndex: "tos", key: "tos" },
    { title: "Freight Invoice (Inv. No.)", dataIndex: "freightInv", key: "freightInv" },
    { title: "Debit Note (DN. No.)", dataIndex: "debitNote", key: "debitNote" },
    { title: "Total Income (BDT.)", dataIndex: "income", key: "income" },
    { title: "Expense Bill (EB. No.)", dataIndex: "expenseBill", key: "expenseBill" },
    { title: "Credit Note (CN. No.)", dataIndex: "creditNote", key: "creditNote" },
    { title: "Total Expense (BDT.)", dataIndex: "expense", key: "expense" },
    { title: "Net Profit (BDT.)", dataIndex: "profit", key: "profit" },
    { title: "C&F Agent Used", dataIndex: "agentUsed", key: "agentUsed" },
    { title: "Business Generated By", dataIndex: "businessBy", key: "businessBy" },
  ];

  return (
    <div className="min-h-screen bg-[#f5f7fa] px-6 py-6 flex flex-col gap-6">
      {/* FILTER CARD */}
      <Card
        size="small"
        className="shadow-sm border border-gray-200 rounded-md"
        bodyStyle={{ padding: 0 }}
      >
        <HeaderTittlePrintFrom title="C&F Volume Statement / Import Sea Filter" />

        <div className="bg-white px-6 py-6 rounded-b-md">
          <Form layout="vertical" className="grid grid-cols-12 gap-x-6 gap-y-4">
            {/* Row 1 */}
            <Form.Item label="Consignee" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
              </Select>
            </Form.Item>

            <Form.Item label="Shipper" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
              </Select>
            </Form.Item>

            <Form.Item label="Origin Agent" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
              </Select>
            </Form.Item>

            <Form.Item label="POL" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
              </Select>
            </Form.Item>

            {/* Row 2 */}
            <Form.Item label="Commodity" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
              </Select>
            </Form.Item>

            <Form.Item label="Destination Agent" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
              </Select>
            </Form.Item>

            <Form.Item label="Business Generated By" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
              </Select>
            </Form.Item>

            <Form.Item label="ETD Date From" className="col-span-12 md:col-span-3">
              <DatePicker className="w-full" format="DD MMMM, YYYY" />
            </Form.Item>

            <Form.Item label="ETD Date To" className="col-span-12 md:col-span-3 md:col-start-10">
              <DatePicker className="w-full" format="DD MMMM, YYYY" />
            </Form.Item>
          </Form>

          <p className="text-xs text-gray-500 mt-2 mb-3 italic">
            * Required Fields
          </p>

          <div className="flex justify-end">
            <Button
              type="primary"
              icon={<SearchOutlined />}
              className="rounded-full px-6 bg-teal-600 hover:bg-teal-700 shadow-sm"
            >
              Search
            </Button>
          </div>
        </div>
      </Card>

      {/* REPORT CARD */}
      <Card
        size="small"
        className="shadow-sm border border-gray-200 rounded-md"
        bodyStyle={{ padding: "1.5rem" }}
      >
        <div className="bg-white rounded-md p-6 text-center">
          <p className="font-semibold text-[15px] text-gray-800 mb-1">
            N2N Supply Chain Solutions Ltd.
          </p>
          <p className="text-xs text-gray-600 underline">
            House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
          </p>
          <p className="text-[11px] mt-2 uppercase tracking-wide text-gray-700">
            C&F VOLUME STATEMENT / IMP. SEA
          </p>

          <div className="flex justify-between text-xs text-left mt-4 mb-3">
            <div>
              <p>Generated By: nahidridwanul@gmail.com</p>
            </div>
            <div className="text-right">
              <p>Print Date: 10/11/2025 01:33 PM</p>
            </div>
          </div>

          <Table
            size="small"
            columns={columns}
            dataSource={[]}
            pagination={false}
            bordered
            scroll={{ x: 2400 }}
          />
        </div>
      </Card>
    </div>
  );
};

export default CnfVolumeStatementImpSeaPage;
