// PartyLedgerPage.jsx
import React, { useState } from "react";
import {
  Card,
  Form,
  Radio,
  Select,
  DatePicker,
  Button,
  Table,
} from "antd";
import {
  ReloadOutlined,
  PrinterOutlined,
  SearchOutlined,
  FolderOpenOutlined,
  CalendarOutlined,
} from "@ant-design/icons";

const { Option } = Select;

const PartyLedgerPage = () => {
  const [partyType, setPartyType] = useState("customer");

  const columns = [
    { title: "Date", dataIndex: "date", key: "date" },
    { title: "Particulars", dataIndex: "particulars", key: "particulars" },
    { title: "Voucher No.", dataIndex: "voucherNo", key: "voucherNo" },
    { title: "Voucher Type", dataIndex: "voucherType", key: "voucherType" },
    { title: "Debit", dataIndex: "debit", key: "debit" },
    { title: "Credit", dataIndex: "credit", key: "credit" },
    { title: "Balance", dataIndex: "balance", key: "balance" },
  ];

  return (
    <div className="min-h-screen ">
      {/* FILTER CARD */}
      <Card
        size="small"
        className="mb-4 border border-[#dfe3e6] rounded-sm"
        bodyStyle={{ padding: 0 }}
      >
       

        {/* Form area */}
        <div className="px-3 py-3 bg-white">
          <Form layout="vertical" className="grid grid-cols-12 gap-4">
            {/* Party Type */}
            <Form.Item
              label="Party Type"
              className="col-span-12 sm:col-span-4"
            >
              <Radio.Group
                value={partyType}
                onChange={(e) => setPartyType(e.target.value)}
              >
                <Radio value="customer">Customer</Radio>
                <Radio value="supplier">Supplier</Radio>
              </Radio.Group>
            </Form.Item>

            {/* Start Date */}
            <Form.Item
              label="Start Date"
              className="col-span-12 sm:col-span-4 sm:col-start-9"
            >
              <DatePicker
                className="w-full"
                format="DD MMMM, YYYY"
                suffixIcon={<CalendarOutlined />}
              />
            </Form.Item>

            {/* Party select */}
            <Form.Item
              label="Party"
              className="col-span-12 sm:col-span-4"
            >
              <Select
                placeholder="(-- Select Party --)"
                allowClear
                showSearch
              >
                <Option value="p1">ABC Trading</Option>
                <Option value="p2">XYZ Supplier</Option>
              </Select>
            </Form.Item>

            {/* End Date */}
            <Form.Item
              label="End Date"
              className="col-span-12 sm:col-span-4 sm:col-start-9"
            >
              <DatePicker
                className="w-full"
                format="DD MMMM, YYYY"
                suffixIcon={<CalendarOutlined />}
              />
            </Form.Item>
          </Form>

          <p className="text-xs text-gray-500 mt-1 mb-2">
            * Required Fields
          </p>

          <div className="flex justify-end">
            <Button
              type="primary"
              icon={<SearchOutlined />}
              className="rounded-full px-5 bg-teal-600 hover:bg-teal-700"
            >
              Search
            </Button>
          </div>
        </div>
      </Card>

      {/* REPORT CARD */}
      <Card
        size="small"
        className="border border-[#dfe3e6] rounded-sm"
        bodyStyle={{ padding: 0 }}
      >
        <div className="bg-white px-3 py-4 text-center">
          <p className="font-semibold text-[14px]">
            N2N Supply Chain Solutions Ltd.
          </p>
          <p className="text-xs underline">
            House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
          </p>
          <p className="text-[11px] mt-1 uppercase tracking-wide">
            PARTY LEDGER REPORT
          </p>
          <p className="text-xs mt-1">
            Period: -------- to --------
          </p>

          {/* top meta */}
          <div className="flex justify-between text-xs mt-4 mb-2">
            <div className="text-left">
              <p>Generated By: nahidridwanul@gmail.com</p>
            </div>
            <div className="text-right">
              <p>Print Date: 10/11/2025 12:03 PM</p>
            </div>
          </div>

          <Table
            size="small"
            columns={columns}
            dataSource={[]}
            pagination={false}
            bordered
          />
        </div>
      </Card>
    </div>
  );
};

export default PartyLedgerPage;
