import React from "react";
import { Card, Form, Select, Button, Table } from "antd";
import { SearchOutlined } from "@ant-design/icons";
import HeaderTittlePrintFrom from "../../SharedAllListFrom/HeaderTitle/HeaderTittlePrintFrom";

const { Option } = Select;

const CnfProfitLossImpSeaPage = () => {
  const columns = [
    { title: "REFERENCE", dataIndex: "reference", key: "reference" },
    { title: "PARTY", dataIndex: "party", key: "party" },
    { title: "ACCOUNT HEAD", dataIndex: "accountHead", key: "accountHead" },
    { title: "UNIT", dataIndex: "unit", key: "unit" },
    { title: "CHARGE/UNIT", dataIndex: "chargeUnit", key: "chargeUnit" },
    { title: "TOTAL AMOUNT (IN BDT.)", dataIndex: "totalAmt", key: "totalAmt" },
  ];

  return (
    <div className="min-h-screen bg-[#f5f7fa] px-6 py-6 flex flex-col gap-6">
      {/* FILTER CARD */}
      <Card
        size="small"
        className="shadow-sm border border-gray-200 rounded-md"
        bodyStyle={{ padding: 0 }}
      >
        {/* Header */}
        <HeaderTittlePrintFrom title="C&F Profit & Loss Statement / Imp. Sea Filter" />

        {/* Filter Form */}
        <div className="bg-white px-6 py-5 rounded-b-md">
          <Form layout="vertical" className="grid grid-cols-12 gap-x-6 gap-y-4">
            <Form.Item
              label="HBL"
              className="col-span-12 md:col-span-6 lg:col-span-4"
            >
              <Select placeholder="(-- Select/None HBL --)">
                <Option value="none">None</Option>
                <Option value="hbl1">HBL-001</Option>
                <Option value="hbl2">HBL-002</Option>
              </Select>
            </Form.Item>
          </Form>

          {/* Notes */}
          <p className="text-xs text-gray-500 mt-1 mb-4 italic">
            * Required Fields
          </p>

          {/* Search Button */}
          <div className="flex justify-end">
            <Button
              type="primary"
              icon={<SearchOutlined />}
              className="rounded-full px-6 py-1 bg-teal-600 hover:bg-teal-700 shadow-sm"
            >
              Search
            </Button>
          </div>
        </div>
      </Card>

      {/* REPORT CARD */}
      <Card
        size="small"
        className="shadow-sm border border-gray-200 rounded-md"
        bodyStyle={{ padding: "1.5rem" }}
      >
        <div className="bg-white rounded-md p-6 text-center">
          {/* Company Header */}
          <p className="font-semibold text-[15px] text-gray-800 mb-1">
            N2N Supply Chain Solutions Ltd.
          </p>
          <p className="text-xs text-gray-600 underline">
            House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
          </p>
          <p className="text-[11px] mt-2 uppercase tracking-wide text-gray-700">
            C&F PROFIT & LOSS STATEMENT / IMP. SEA
          </p>

          {/* Meta Section */}
          <div className="flex justify-between text-xs text-left mt-6 mb-3 gap-20">
            {/* Left column */}
            <div className="space-y-[3px] leading-relaxed">
              <p>Generated By: <span className="font-medium text-gray-800">nahidridwanul@gmail.com</span></p>
              <p>HBL :</p>
              <p>SHIPPER :</p>
              <p>ORIGIN AGENT :</p>
              <p>POL :</p>
              <p>ETD DATE :</p>
              <p>TOTAL VOL :</p>
              <p>TOTAL QTY :</p>
            </div>

            {/* Right column */}
            <div className="space-y-[3px] leading-relaxed text-right">
              <p>Print Date: <span className="font-medium text-gray-800">10/11/2025 01:12 PM</span></p>
              <p>MBL :</p>
              <p>CONSIGNEE :</p>
              <p>DESTINATION AGENT :</p>
              <p>POD :</p>
              <p>ETA DATE :</p>
              <p>JOB NO. :</p>
              <p>TOTAL GWT :</p>
            </div>
          </div>

          {/* Table */}
          <Table
            size="small"
            columns={columns}
            dataSource={[]}
            pagination={false}
            bordered
            className="mt-4"
          />
        </div>
      </Card>
    </div>
  );
};

export default CnfProfitLossImpSeaPage;
