// ProductWiseSalePage.jsx
import React from "react";
import {
  Card,
  Form,
  DatePicker,
  Button,
  Table,
} from "antd";
import {
  ReloadOutlined,
  PrinterOutlined,
  SearchOutlined,
  FolderOpenOutlined,
  CalendarOutlined,
} from "@ant-design/icons";

const ProductWiseSalePage = () => {
  const columns = [
    { title: "Category / Product Details", dataIndex: "product", key: "product" },
    { title: "Date", dataIndex: "date", key: "date" },
    { title: "Number", dataIndex: "number", key: "number" },
    { title: "Branch", dataIndex: "branch", key: "branch" },
    { title: "Quantity", dataIndex: "qty", key: "qty" },
    { title: "Unit Price", dataIndex: "unitPrice", key: "unitPrice" },
    { title: "Total Amount", dataIndex: "total", key: "total" },
  ];

  return (
    <div className="min-h-screen ">
      {/* FILTER CARD */}
      <Card
        size="small"
        className="mb-4 border border-[#dfe3e6] rounded-sm"
        bodyStyle={{ padding: 0 }}
      >
       

        {/* Form */}
        <div className="px-3 py-3 bg-white">
          <Form layout="vertical" className="grid grid-cols-12 gap-4">
            {/* Start Date */}
            <Form.Item
              label="Start Date"
              className="col-span-12 md:col-span-6"
            >
              <DatePicker
                className="w-full"
                format="DD MMMM, YYYY"
                suffixIcon={<CalendarOutlined />}
              />
            </Form.Item>

            {/* End Date */}
            <Form.Item
              label="End Date"
              className="col-span-12 md:col-span-6"
            >
              <DatePicker
                className="w-full"
                format="DD MMMM, YYYY"
                suffixIcon={<CalendarOutlined />}
              />
            </Form.Item>
          </Form>

          <p className="text-xs text-gray-500 mt-1 mb-2">
            * Required Fields
          </p>

          <div className="flex justify-end">
            <Button
              type="primary"
              icon={<SearchOutlined />}
              className="rounded-full px-5 bg-teal-600 hover:bg-teal-700"
            >
              Search
            </Button>
          </div>
        </div>
      </Card>

      {/* REPORT CARD */}
      <Card
        size="small"
        className="border border-[#dfe3e6] rounded-sm"
        bodyStyle={{ padding: 0 }}
      >
        <div className="bg-white px-3 py-4 text-center">
          <p className="font-semibold text-[14px]">
            N2N Supply Chain Solutions Ltd.
          </p>
          <p className="text-xs underline">
            House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
          </p>
          <p className="text-[11px] mt-1 uppercase tracking-wide">
            PRODUCT WISE SALE REPORT
          </p>
          <p className="text-xs mt-1">Period: -------- to --------</p>

          {/* meta */}
          <div className="flex justify-between text-xs mt-4 mb-2">
            <div className="text-left">
              <p>Generated By: nahidridwanul@gmail.com</p>
            </div>
            <div className="text-right">
              <p>Print Date: 10/11/2025 12:47 PM</p>
            </div>
          </div>

          <Table
            size="small"
            columns={columns}
            dataSource={[]}
            pagination={false}
            bordered
          />
        </div>
      </Card>
    </div>
  );
};

export default ProductWiseSalePage;
