import React from "react";
import {
  Card,
  Form,
  Select,
  DatePicker,
  Button,
  Table,
} from "antd";
import {
  ReloadOutlined,
  PrinterOutlined,
  SearchOutlined,
  FolderOpenOutlined,
  CalendarOutlined,
} from "@ant-design/icons";

const { Option } = Select;

const SalesPurchaseDetailsPage = () => {
  const columns = [
    { title: "S/L. No.", dataIndex: "sl", key: "sl", width: 80 },
    { title: "Date", dataIndex: "date", key: "date" },
    { title: "Voucher No.", dataIndex: "voucherNo", key: "voucherNo" },
    { title: "Supplier", dataIndex: "supplier", key: "supplier" },
    { title: "Branch", dataIndex: "branch", key: "branch" },
    { title: "Product", dataIndex: "product", key: "product" },
    { title: "Description", dataIndex: "description", key: "description" },
    { title: "Quantity", dataIndex: "qty", key: "qty" },
    { title: "Price", dataIndex: "price", key: "price" },
    { title: "Amount", dataIndex: "amount", key: "amount" },
    { title: "Grand Total", dataIndex: "grandTotal", key: "grandTotal" },
    { title: "Paid Amount", dataIndex: "paid", key: "paid" },
    { title: "Due Amount", dataIndex: "due", key: "due" },
  ];

  return (
    <div className="min-h-screen ">
      {/* FILTER CARD */}
      <Card
        size="small"
        className="mb-4 border border-[#dfe3e6] rounded-sm"
        bodyStyle={{ padding: 0 }}
      >
       

        {/* Form */}
        <div className="px-3 py-3 bg-white">
          <Form layout="vertical" className="grid grid-cols-12 gap-4">
            {/* Row 1 */}
            <Form.Item label="Party" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
                <Option value="p1">ABC Customer</Option>
              </Select>
            </Form.Item>

            <Form.Item label="Branch" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
                <Option value="b1">Banani</Option>
              </Select>
            </Form.Item>

            <Form.Item label="Employee" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
                <Option value="e1">Sales Rep 1</Option>
              </Select>
            </Form.Item>

            <Form.Item label="Sales Type" className="col-span-12 md:col-span-3">
              <Select defaultValue="ALL">
                <Option value="ALL">ALL</Option>
                <Option value="cash">Cash</Option>
                <Option value="credit">Credit</Option>
              </Select>
            </Form.Item>

            {/* Row 2 - Centered Dates */}
            <div className="col-span-12 flex flex-col md:flex-row justify-center items-center gap-4 mt-2">
              <Form.Item label="Start Date" className="m-0 w-full md:w-1/4">
                <DatePicker
                  className="w-full"
                  format="DD MMMM, YYYY"
                  suffixIcon={<CalendarOutlined />}
                />
              </Form.Item>

              <Form.Item label="End Date" className="m-0 w-full md:w-1/4">
                <DatePicker
                  className="w-full"
                  format="DD MMMM, YYYY"
                  suffixIcon={<CalendarOutlined />}
                />
              </Form.Item>
            </div>
          </Form>

          <p className="text-xs text-gray-500 mt-1 mb-2">
            * Required Fields
          </p>

          <div className="flex justify-end">
            <Button
              type="primary"
              icon={<SearchOutlined />}
              className="rounded-full px-5 bg-teal-600 hover:bg-teal-700"
            >
              Search
            </Button>
          </div>
        </div>
      </Card>

      {/* REPORT CARD */}
      <Card
        size="small"
        className="border border-[#dfe3e6] rounded-sm"
        bodyStyle={{ padding: 0 }}
      >
        <div className="bg-white px-3 py-4 text-center">
          <p className="font-semibold text-[14px]">
            N2N Supply Chain Solutions Ltd.
          </p>
          <p className="text-xs underline">
            House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
          </p>
          <p className="text-[11px] mt-1 uppercase tracking-wide">
            SALES DETAILS REPORT
          </p>
          <p className="text-xs mt-1">Period: -------- to --------</p>

          {/* metadata row */}
          <div className="flex justify-between text-xs mt-4 mb-2">
            <div className="text-left">
              <p>Generated By: nahidridwanul@gmail.com</p>
              <p>Party: ---------</p>
            </div>
            <div className="text-right">
              <p>Print Date: 10/11/2025 12:24 PM</p>
            </div>
          </div>

          <Table
            size="small"
            columns={columns}
            dataSource={[]}
            pagination={false}
            bordered
            scroll={{ x: 1200 }}
          />
        </div>
      </Card>
    </div>
  );
};

export default SalesPurchaseDetailsPage;
