import React, { useState } from "react";
import { Row, Col, DatePicker, Button, Table } from "antd";
import {
  FolderOpenOutlined,
  RedoOutlined,
  PrinterOutlined,
  SearchOutlined,
} from "@ant-design/icons";
import dayjs from "dayjs";

const BalanceSheetFilter = () => {
  const [startDate, setStartDate] = useState(dayjs("2025-10-29"));
  const [endDate, setEndDate] = useState(dayjs("2025-11-05"));

  const handleSearch = () => {
    console.log({
      start: startDate?.format("YYYY-MM-DD"),
      end: endDate?.format("YYYY-MM-DD"),
    });
  };

  const handleReset = () => {
    setStartDate(dayjs("2025-10-29"));
    setEndDate(dayjs("2025-11-05"));
  };

  // we'll just show empty table body, like your screenshot
  const columns = [
    {
      title: "",
      dataIndex: "blank1",
      width: 40,
    },
    {
      title: "LIABILITIES",
      dataIndex: "liabilities",
    },
    {
      title: "AMOUNT",
      dataIndex: "liabAmount",
      width: 120,
      align: "right",
    },
    {
      title: "ASSETS",
      dataIndex: "assets",
    },
    {
      title: "AMOUNT",
      dataIndex: "assetAmount",
      width: 120,
      align: "right",
    },
  ];

  return (
    <div style={{ background: "#fff", border: "1px solid #d9d9d9" }}>
      {/* top title bar */}
     
      {/* filter row */}
      <div style={{ padding: "12px 14px 4px" }}>
        <Row gutter={16} align="bottom">
          <Col xs={24} md={8}>
            <div style={{ fontSize: 12, marginBottom: 4 }}>Start Date</div>
            <DatePicker
              value={startDate}
              onChange={setStartDate}
              format="DD MMMM, YYYY"
              style={{ width: "100%" }}
            />
          </Col>
          <Col xs={24} md={8}>
            <div style={{ fontSize: 12, marginBottom: 4 }}>End Date</div>
            <DatePicker
              value={endDate}
              onChange={setEndDate}
              format="DD MMMM, YYYY"
              style={{ width: "100%" }}
            />
          </Col>
          <Col
            xs={24}
            md={8}
            style={{
              display: "flex",
              justifyContent: "flex-end",
              alignItems: "flex-end",
            }}
          >
            <Button
              type="primary"
              icon={<SearchOutlined />}
              onClick={handleSearch}
              style={{
                background: "#0ea5e9",
                border: "none",
                height: 38,
                width: 120,
              }}
            >
              Search
            </Button>
          </Col>
        </Row>

        <div style={{ fontSize: 11, color: "#b91c1c", marginTop: 8 }}>
          * Required Fields
        </div>
      </div>

      {/* report box */}
      <div style={{ padding: 14 }}>
        <div
          style={{
            border: "1px solid #d9d9d9",
            background: "#fff",
            minHeight: 140,
          }}
        >
          <div style={{ padding: "10px 12px 0" }}>
            <div style={{ textAlign: "center", fontWeight: 600 }}>
              N2N Supply Chain Solutions Ltd.
            </div>
            <div
              style={{
                textAlign: "center",
                fontSize: 12,
                textDecoration: "underline",
              }}
            >
              House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
            </div>
            <div
              style={{
                textAlign: "center",
                fontWeight: 500,
                marginTop: 4,
              }}
            >
              BALANCE SHEET REPORT
            </div>
            <div
              style={{
                textAlign: "center",
                fontSize: 11,
                marginBottom: 6,
              }}
            >
              Period: -------- to --------
            </div>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                fontSize: 11,
                marginBottom: 6,
              }}
            >
              <span>Generated By: nahidridwanul@gmail.com</span>
              <span>Print Date: 05/11/2025 07:54 PM</span>
            </div>
          </div>

          {/* table header like screenshot */}
          <Table
            columns={columns}
            dataSource={[]}
            pagination={false}
            size="small"
            style={{ marginTop: 4 }}
            locale={{ emptyText: " " }}
            bordered
          />
        </div>
      </div>
    </div>
  );
};

export default BalanceSheetFilter;
