import React, { useState } from "react";
import {
  Row,
  Col,
  Select,
  DatePicker,
  Button,
  Input,
  Typography,
  Table,
  Space,
  Card,
} from "antd";
import {
  SearchOutlined,
  ReloadOutlined,
  PrinterOutlined,
  FileTextOutlined,
} from "@ant-design/icons";
import dayjs from "dayjs";

const { Option } = Select;
const { Text } = Typography;

const accounts = [
  { label: "(-- Select/None --)", value: "" },
  { label: "Eastern Bank PLC", value: "ebl" },
  { label: "Petty Cash", value: "petty" },
  { label: "Prime Bank PLC", value: "prime" },
];

const BankStatementFilter = () => {
  const [account, setAccount] = useState("");
  const [startDate, setStartDate] = useState(dayjs("2025-10-29"));
  const [endDate, setEndDate] = useState(dayjs("2025-11-05"));

  const handleSearch = () => {
    console.log({
      account,
      startDate: startDate?.format("YYYY-MM-DD"),
      endDate: endDate?.format("YYYY-MM-DD"),
    });
  };

  const handleReset = () => {
    setAccount("");
    setStartDate(dayjs("2025-10-29"));
    setEndDate(dayjs("2025-11-05"));
  };

  // dummy columns like screenshot
  const columns = [
    { title: "Date", dataIndex: "date", width: 120 },
    { title: "Particulars", dataIndex: "particulars" },
    { title: "Voucher No.", dataIndex: "voucherNo", width: 130 },
    { title: "Voucher Type", dataIndex: "voucherType", width: 140 },
    {
      title: "Debit Amount",
      dataIndex: "debit",
      width: 120,
      align: "right",
    },
    {
      title: "Credit Amount",
      dataIndex: "credit",
      width: 120,
      align: "right",
    },
  ];

  return (
    <div style={{ background: "#fff", border: "1px solid #d9d9d9" }}>
     

      {/* filter body */}
      <div style={{ padding: "12px 14px 6px" }}>
        <Row gutter={16}>
          <Col xs={24} md={10} lg={8}>
            <div style={{ fontSize: 12, marginBottom: 4 }}>Account Chart</div>
            <Select
              showSearch
              value={account}
              onChange={setAccount}
              placeholder="(-- Select/None --)"
              optionFilterProp="label"
              style={{ width: "100%" }}
            >
              {accounts.map((a) => (
                <Option key={a.value} value={a.value} label={a.label}>
                  {a.label}
                </Option>
              ))}
            </Select>
            <div style={{ fontSize: 11, color: "#b91c1c", marginTop: 6 }}>
              * Required Fields
            </div>
          </Col>

          <Col xs={12} md={7} lg={5}>
            <div style={{ fontSize: 12, marginBottom: 4 }}>Start Date</div>
            <DatePicker
              value={startDate}
              onChange={setStartDate}
              format="DD MMMM, YYYY"
              style={{ width: "100%" }}
            />
          </Col>
          <Col xs={12} md={7} lg={5}>
            <div style={{ fontSize: 12, marginBottom: 4 }}>End Date</div>
            <DatePicker
              value={endDate}
              onChange={setEndDate}
              format="DD MMMM, YYYY"
              style={{ width: "100%" }}
            />
          </Col>

          <Col xs={24} md={24} lg={6} style={{ display: "flex", alignItems: "flex-end" }}>
            <Button
              type="primary"
              icon={<SearchOutlined />}
              onClick={handleSearch}
              style={{
                background: "#0ea5e9",
                border: "none",
                height: 38,
                marginLeft: "auto",
              }}
            >
              Search
            </Button>
          </Col>
        </Row>
      </div>

      {/* report box */}
      <div style={{ padding: 14 }}>
        <div
          style={{
            border: "1px solid #d9d9d9",
            minHeight: 140,
            background: "#fff",
          }}
        >
          <div style={{ padding: "10px 12px 0" }}>
            <div style={{ fontWeight: 600, textAlign: "center" }}>
              Brain Solutions Ltd.
            </div>
            <div style={{ textAlign: "center", fontSize: 12, marginBottom: 4 }}>
              House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
            </div>
            <div style={{ textAlign: "center", fontWeight: 500, marginBottom: 6 }}>
              BANK STATEMENT REPORT
            </div>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                fontSize: 11,
                marginBottom: 6,
              }}
            >
              <span>Generated By: nahidridwanul@gmail.com</span>
              <span>Print Date: 05/11/2025 06:48 PM</span>
            </div>
            <div style={{ display: "flex", gap: 8, fontSize: 11 }}>
              <span>Chart of Accounts: ----------- </span>
              <span>Period: -------- to --------</span>
            </div>
          </div>

          {/* table */}
          <Table
            columns={columns}
            dataSource={[]}
            size="small"
            pagination={false}
            style={{ marginTop: 10 }}
            locale={{ emptyText: " " }}
          />
          {/* empty-row border like screenshot */}
          <div style={{ borderTop: "1px solid #d9d9d9" }} />
        </div>
      </div>
    </div>
  );
};

export default BankStatementFilter;
