import React, { useState } from "react";
import {
  Row,
  Col,
  Radio,
  Select,
  Button,
} from "antd";
import {
  FolderOpenOutlined,
  RedoOutlined,
  PrinterOutlined,
  SearchOutlined,
} from "@ant-design/icons";

const { Option } = Select;

const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const years = ["2025", "2024", "2023", "2022"];

const ExpenditureSummaryFilter = () => {
  const [mode, setMode] = useState("month");
  const [month, setMonth] = useState("November");
  const [year, setYear] = useState("2025");

  const handleSearch = () => {
    console.log({ mode, month, year });
  };

  const handleReset = () => {
    setMode("month");
    setMonth("November");
    setYear("2025");
  };

  return (
    <div
      style={{
        background: "#fff",
        border: "1px solid #d0e6f5",
        borderRadius: 4,
      }}
    >
     

      {/* filter area */}
      <div style={{ padding: "12px 12px 0" }}>
        <Row gutter={12} align="middle">
          {/* Month block */}
          <Col xs={24} md={8}>
            <div
              style={{ display: "flex", gap: 10, alignItems: "center" }}
            >
              <Radio
                checked={mode === "month"}
                onChange={() => setMode("month")}
              />
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 12, marginBottom: 4 }}>Month</div>
                <Select
                  value={month}
                  onChange={setMonth}
                  disabled={mode !== "month"}
                  style={{ width: "100%" }}
                  size="middle"
                >
                  {months.map((m) => (
                    <Option key={m} value={m}>
                      {m}
                    </Option>
                  ))}
                </Select>
              </div>
            </div>
          </Col>

          {/* Year block */}
          <Col xs={24} md={8}>
            <div
              style={{ display: "flex", gap: 10, alignItems: "center" }}
            >
              <Radio
                checked={mode === "year"}
                onChange={() => setMode("year")}
              />
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 12, marginBottom: 4 }}>Year</div>
                <Select
                  value={year}
                  onChange={setYear}
                  disabled={mode !== "year"}
                  style={{ width: "100%" }}
                  size="middle"
                >
                  {years.map((y) => (
                    <Option key={y} value={y}>
                      {y}
                    </Option>
                  ))}
                </Select>
              </div>
            </div>
          </Col>

          {/* empty col just to balance row */}
          <Col xs={24} md={8}>
            <div style={{ fontSize: 11, color: "#be123c" }}>* Required Fields</div>
          </Col>
        </Row>
      </div>

      {/* search btn */}
      <div
        style={{
          padding: "6px 12px 10px",
          display: "flex",
          justifyContent: "flex-end",
        }}
      >
        <Button
          type="primary"
          icon={<SearchOutlined />}
          onClick={handleSearch}
          style={{ background: "#0ea5e9", border: "none" }}
        >
          Search
        </Button>
      </div>

      {/* report box */}
      <div style={{ padding: 12 }}>
        <div
          style={{
            border: "1px solid #d9e2ec",
            background: "#fff",
            minHeight: 130,
          }}
        >
          <div style={{ padding: "10px 12px 0" }}>
            <div style={{ textAlign: "center", fontWeight: 600 }}>
              N2N Supply Chain Solutions Ltd.
            </div>
            <div
              style={{
                textAlign: "center",
                fontSize: 12,
                textDecoration: "underline",
              }}
            >
              House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
            </div>
            <div
              style={{
                textAlign: "center",
                fontSize: 12,
                fontWeight: 600,
                marginTop: 4,
              }}
            >
              EXPENDITURE SUMMARY REPORT
            </div>

            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                fontSize: 11,
                marginTop: 12,
                borderTop: "1px solid #d9d9d9",
                paddingTop: 6,
              }}
            >
              <span>Generated By: nahidridwanul@gmail.com</span>
              <span>Print Date: 05/11/2025 07:13 PM</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExpenditureSummaryFilter;
