import React, { useState } from "react";
import { Row, Col, DatePicker, Button, Table } from "antd";
import {
  FolderOpenOutlined,
  RedoOutlined,
  PrinterOutlined,
  SearchOutlined,
} from "@ant-design/icons";
import dayjs from "dayjs";

const JournalListFilter = () => {
  const [startDate, setStartDate] = useState(dayjs("2025-10-29"));
  const [endDate, setEndDate] = useState(dayjs("2025-11-05"));

  const handleSearch = () => {
    console.log({
      startDate: startDate?.format("YYYY-MM-DD"),
      endDate: endDate?.format("YYYY-MM-DD"),
    });
  };

  const handleReset = () => {
    setStartDate(dayjs("2025-10-29"));
    setEndDate(dayjs("2025-11-05"));
  };

  const columns = [
    { title: "S/L No.", dataIndex: "sl", width: 80, align: "center" },
    { title: "Date", dataIndex: "date", width: 140 },
    { title: "Number", dataIndex: "number", width: 150 },
    { title: "Chart of Accounts", dataIndex: "account" },
    {
      title: "Debit Tk.",
      dataIndex: "debit",
      align: "right",
      width: 120,
    },
    {
      title: "Credit Tk.",
      dataIndex: "credit",
      align: "right",
      width: 120,
    },
  ];

  return (
    <div style={{ background: "#fff", border: "1px solid #d9d9d9" }}>
      

      {/* Filter Section */}
      <div style={{ padding: "12px 14px 4px" }}>
        <Row gutter={16} align="bottom">
          <Col xs={24} md={8}>
            <div style={{ fontSize: 12, marginBottom: 4 }}>Start Date</div>
            <DatePicker
              value={startDate}
              onChange={setStartDate}
              format="DD MMMM, YYYY"
              style={{ width: "100%" }}
            />
          </Col>

          <Col xs={24} md={8}>
            <div style={{ fontSize: 12, marginBottom: 4 }}>End Date</div>
            <DatePicker
              value={endDate}
              onChange={setEndDate}
              format="DD MMMM, YYYY"
              style={{ width: "100%" }}
            />
          </Col>

          <Col
            xs={24}
            md={8}
            style={{
              display: "flex",
              alignItems: "flex-end",
              justifyContent: "flex-end",
            }}
          >
            <Button
              type="primary"
              icon={<SearchOutlined />}
              onClick={handleSearch}
              style={{
                background: "#0ea5e9",
                border: "none",
                height: 38,
                width: 120,
              }}
            >
              Search
            </Button>
          </Col>
        </Row>

        <div style={{ fontSize: 11, color: "#b91c1c", marginTop: 8 }}>
          * Required Fields
        </div>
      </div>

      {/* Report Section */}
      <div style={{ padding: 14 }}>
        <div
          style={{
            border: "1px solid #d9d9d9",
            background: "#fff",
            minHeight: 140,
          }}
        >
          <div style={{ padding: "10px 12px 0" }}>
            <div style={{ textAlign: "center", fontWeight: 600 }}>
              N2N Supply Chain Solutions Ltd.
            </div>
            <div
              style={{
                textAlign: "center",
                fontSize: 12,
                marginBottom: 4,
                textDecoration: "underline",
              }}
            >
              House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
            </div>
            <div style={{ textAlign: "center", fontWeight: 500, marginBottom: 6 }}>
              JOURNAL LIST REPORT
            </div>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                fontSize: 11,
                marginBottom: 6,
              }}
            >
              <span>Generated By: nahidridwanul@gmail.com</span>
              <span>Print Date: 05/11/2025 07:31 PM</span>
            </div>
            <div style={{ fontSize: 11, marginBottom: 4 }}>
              Period: -------- to --------
            </div>
          </div>

          {/* Table */}
          <Table
            columns={columns}
            dataSource={[]}
            size="small"
            pagination={false}
            style={{ marginTop: 10 }}
            locale={{ emptyText: " " }}
          />
          <div style={{ borderTop: "1px solid #d9d9d9" }} />
        </div>
      </div>
    </div>
  );
};

export default JournalListFilter;
