// StockReorderPage.jsx
import React from "react";
import {
  Form,
  Select,
  DatePicker,
  Button,
  Table,
  Card,
  Space,
} from "antd";
import {
  ReloadOutlined,
  PrinterOutlined,
  SearchOutlined,
  FolderOpenOutlined,
} from "@ant-design/icons";

const { Option } = Select;

const StockReorderPage = () => {
  // dummy columns to match screenshot
  const columns = [
    {
      title: "Category/Product",
      dataIndex: "category",
      key: "category",
    },
    {
      title: "Country",
      dataIndex: "country",
      key: "country",
    },
    {
      title: "Brand",
      dataIndex: "brand",
      key: "brand",
    },
    {
      title: "Branch",
      dataIndex: "branch",
      key: "branch",
    },
    {
      title: "Re-Order Level",
      dataIndex: "reorder",
      key: "reorder",
    },
    {
      title: "Current Stock",
      dataIndex: "currentStock",
      key: "currentStock",
    },
  ];

  return (
    <div className="min-h-screen ">
      {/* FILTER CARD */}
      <Card
        size="small"
        className="mb-4 border border-[#dfe3e6] rounded-2xl"
        bodyStyle={{ padding: 0 }}
      >
       

        {/* Form */}
        <div className="px-3 py-3 bg-white">
          <Form layout="vertical" className="grid grid-cols-12 gap-4">
            {/* Category */}
            <Form.Item
              label="Category"
              className="col-span-12 sm:col-span-3"
            >
              <Select size="middle" defaultValue="ALL">
                <Option value="ALL">ALL</Option>
                <Option value="cat1">Category 1</Option>
              </Select>
            </Form.Item>

            {/* Country */}
            <Form.Item label="Country" className="col-span-12 sm:col-span-3">
              <Select size="middle" defaultValue="ALL">
                <Option value="ALL">ALL</Option>
                <Option value="bd">Bangladesh</Option>
              </Select>
            </Form.Item>

            {/* Unit */}
            <Form.Item label="Unit" className="col-span-12 sm:col-span-3">
              <Select size="middle" defaultValue="ALL">
                <Option value="ALL">ALL</Option>
                <Option value="unit1">Unit 1</Option>
              </Select>
            </Form.Item>

            {/* End Date */}
            <Form.Item label="End Date" className="col-span-12 sm:col-span-3">
              <DatePicker className="w-full" format="DD MMMM, YYYY" />
            </Form.Item>
          </Form>

          <p className="text-xs text-gray-500 mt-1 mb-2">
            * Required Fields
          </p>

          <div className="flex justify-end">
            <Button
              type="primary"
              icon={<SearchOutlined />}
              className="rounded-full px-5 bg-teal-600 hover:bg-teal-700"
            >
              Search
            </Button>
          </div>
        </div>
      </Card>

      {/* REPORT PANEL */}
      <Card
        size="small"
        className="border border-[#dfe3e6] rounded-sm"
        bodyStyle={{ padding: 0 }}
      >
        {/* Just like screenshot: inside white area */}
        <div className="bg-white px-3 py-4 text-center">
          <p className="font-semibold text-[14px]">
            N2N Supply Chain Solutions Ltd.
          </p>
          <p className="text-xs underline">
            House# 7 (4th Floor), Road# 2/1, Banani, Dhaka, Bangladesh
          </p>
          <p className="text-[11px] mt-1 uppercase tracking-wide">
            STOCK RE-ORDER REPORT
          </p>

          {/* meta row */}
          <div className="flex justify-between text-xs mt-4 mb-2">
            <div className="text-left">
              <p>Generated By: nahidridwanul@gmail.com</p>
              <p>Category: --------</p>
              <p>Branch: ---------</p>
            </div>
            <div className="text-right">
              <p>Print Date: 10/11/2025 11:49 AM</p>
              <p>Unit: --------</p>
              <p>Upto: --------</p>
            </div>
          </div>

          <div className="text-xs mb-2">
            <p>Country: --------</p>
            <p>Brand: ---------</p>
          </div>

          {/* table */}
          <Table
            size="small"
            columns={columns}
            dataSource={[]}
            pagination={false}
            bordered
          />
        </div>
      </Card>
    </div>
  );
};

export default StockReorderPage;
